vcinema/cinema/urls.py
from django.urls import path
from . import views

app_name = 'cinema'
urlpatterns = [
    path('', views.index, name='main'),
    path('detail/<str:pk>/', views.detail, name='detail'),
    path('register/', views.register, name='register'),
    path('authorize/', views.authorize, name='authorize'),
    path('logout/', views.logout_view, name='logout')
]

vcinema/vcinema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('cinema.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vcinema/cinema/models.py
from django.db import models


# Create your models here.
# class Directory
# class Genre
class Movies(models.Model):
    title = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='movies/%Y', blank=True)
    rating = models.FloatField()
    release_date = models.DateField()
    age_rest = models.IntegerField()
    directory = models.CharField(max_length=100)
    video = models.URLField(max_length=128)
    article = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('release_date',)
        verbose_name_plural = 'Movies'
        verbose_name = 'Movie'


class Comments(models.Model):
    name = models.CharField(max_length=100)
    movie = models.ForeignKey('Movies', on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Comments'
        verbose_name = 'Comment'

vcinema/cinema/forms.py
from .models import Comments
from django.forms import ModelForm
from django import forms


class CommentsForm(ModelForm):
    class Meta:
        model = Comments
        fields = ["name", "movie", "comment"]

vcinema/cinema/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from .models import Movies, Comments
from .forms import CommentsForm


def index(request):
    movies = Movies.objects.all()[:10]
    context = {
        'movies': movies,
    }
    return render(request, "cinema/index.html", context)


def detail(request, pk):
    movie = Movies.objects.get(id=pk)

    if request.method == 'POST' and request.user.is_authenticated:
        username = request.user.username
        f = {
            'name': username,
            'movie': movie,
            'comment': request.POST['comment']
        }
        form = CommentsForm(f)
        if form.is_valid():
            form.save()
        return redirect(reverse("cinema:detail", args=(pk, )))

    comments = Comments.objects.filter(movie__pk=pk)
    context = {
        'movie': movie,
        'comments': comments
    }
    return render(request, "cinema/detail.html", context)


def register(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        repass = request.POST['repass']
        if repass == password:
            try:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()
                user = authenticate(username=username, password=password)
                if user != None:
                    login(request, user)
                    return redirect(reverse("cinema:main"))
                else:
                    return redirect(reverse("cinema:authorize"))
            except Exception as e:
                print(e)
                return redirect(reverse("cinema:register"))
        else:
            return redirect(reverse("cinema:register"))
    return render(request, "cinema/registration.html")


def authorize(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user != None:
            login(request, user)
            return redirect(reverse("cinema:main"))
        else:
            return redirect(reverse("cinema:authorize"))
    return render(request, "cinema/login.html")

def logout_view(request):
    logout(request)
    return redirect(reverse("cinema:main"))

vcinema/cinema/templates/cinema/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>VCinema</title>

	<link rel="shortcut icon" href="{% static 'files/logo.jpg' %}">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<!-- Latest compiled and minified CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">

	<!-- Latest compiled JavaScript -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>

	{% block csslink %}{% endblock %}

</head>
<body>
	<header class="container-fluid">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-1"></div>
				<div class="col-sm-7"><h1 align="left"><a href="{% url 'cinema:main' %}">VCinema</a></h1></div>
  				<div class="col-sm-2">
  					<ul class="nav justify-content-center">
						{% if user.is_authenticated %}
						<li class="nav-item">
  							<a class="nav-link disabled">{{ user.username }}</a>
  						</li>
						{% else %}
  						<li class="nav-item">
  							<a class="nav-link" href="{% url 'cinema:authorize' %}">sign in</a>
  						</li>
						{% endif %}
  					</ul>
  				</div>
  				<div class="col-sm-2">
  					<ul class="nav">
						{% if user.is_authenticated %}
						<li class="nav-item">
  							<a class="nav-link" href="{% url 'cinema:logout' %}">log out</a>
  						</li>
						{% else %}
						<li class="nav-item">
  							<a class="nav-link" href="{% url 'cinema:register' %}">registration</a>
  						</li>
						{% endif %}
  					</ul>
  				</div>
			</div>
		</div>
	</header>
	{% block maincontent %}{% endblock %}
	<footer class="container-fluid">
		<div class="row">
			<div class="col-sm-1"></div>
			<div class="col-sm-9">
				<ul class="nav">
  					<li class="nav-item">
    					<a class="nav-link" href="#">copyright</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">advertisers</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">channels</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">TG channel</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">VK group</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">Youtube channel</a>
  					</li>
				</ul>
			</div>
			<div class="col-sm-2">© &emsp; 2022 &emsp; VCinema.com</div>
		</div>
		<section id="foot">Copyright © 2022 &nbsp; @aiskido</section>
	</footer>
</body>
</html>

vcinema/cinema/templates/cinema/detail.html
{% extends 'cinema/base.html' %}
{% load static %}
{% block csslink %}
<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
{% endblock %}
{% block maincontent %}
	<main class="container-fluid">
		<div class="row" id="deta">
			<div class="col-sm-1"></div>
			<div class="col-sm-7">
				<div class="container-fluid" align="center">
					<h2>{{ movie.title }}</h2>
				</div>
				<div id="deta_info">
					<table>
						<tr>
							<td>Rating:</td>
							<td>{{ movie.rating }}</td>
						</tr>
						<tr>
							<td>Date:</td>
							<td>{{ movie.release_date }}</td>
						</tr>
						<tr>
							<td>Age:</td>
							<td>{{ movie.age_rest }}+</td>
						</tr>
						<tr>
							<td>Directory:</td>
							<td>{{ movie.directory }}</td>
						</tr>
					</table>
				</div>
				<div class="container-fluid">
					<img src="{{ movie.photo.url }}">
				</div>
				<div class="container-fluid">
					<h4>Overview</h4>
					<p>{{ movie.article }}</p>
				</div>
				<div align="center" class="container-fluid">
					<iframe id="deta_vid" src="{{ movie.video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
				</div>
				<div class="container-fluid" id="deta_com">
					<h3>Comments:</h3>
					<form method="post">
						{% csrf_token %}
						<textarea class="form-control" rows="1" id="comment" name="comment" placeholder="leave comment.."></textarea>
						<button type="submit" class="btn btn-primary">Submit</button>
					</form>
					<ul>
						{% for com in comments %}
                  		<li>
                  			<h5>{{ com.name }}</h5>
                   			<span>{{ com.comment }}</span>
                  		</li>
                  		<hr>
						{% endfor %}
              		</ul>
				</div>
			</div>
			<div class="col-sm-3">
				<h3 align="center">Similar</h3>
				<hr>
			</div>
		</div>
	</main>
{% endblock %}

vcinema/cinema/templates/cinema/index.html
{% extends 'cinema/base.html' %}
{% load static %}
{% block csslink %}
<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
{% endblock %}
{% block maincontent %}
	<main class="container-fluid">
		<div class="row" id="head_nav">
			<div class="col-sm-1"></div>
			<div class="col-sm-7">
				<form>
				  <div class="input-group" id="head_search">
				    <input type="text" class="form-control" placeholder="Search">
				    <div class="input-group-btn">
				      <button class="btn btn-default" type="submit">
				        <i class="fa fa-search"></i>
				      </button>
				    </div>
				  </div>
				</form>
				<ul class="nav">
  					<li class="nav-item">
    					<a class="nav-link" href="#">Films</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">TV series</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">Cartoons</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">Trends</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">2022</a>
  					</li>
  					<li class="nav-item">
    					<a class="nav-link" href="#">2021</a>
  					</li>
				</ul>
				<h2>Latest added:</h2>
				{% for movie in movies %}
				<div class="container-fluid">
					<div class="lst_m_head"><a href="{% url 'cinema:detail' movie.id %}"><h5>{{ movie.title }}</h5></a></div>
					<div class="lst_movie">
						<div class="lst_avatar"><img src="{{ movie.photo.url }}" width="250px" height="350px"></div>
						<div class="lst_text">
							<table>
								<tr>
									<td>Rating:</td>
									<td><i>{{ movie.rating }}</i></td>
								</tr>
								<tr>
									<td>Date:</td>
									<td><i>{{ movie.release_date }}</i></td>
								</tr>
								<tr>
									<td>Age:</td>
									<td><i>{{ movie.age_rest }}+</i></td>
								</tr>
								<tr>
									<td>Directory:</td>
									<td><i>{{ movie.directory }}</i></td>
								</tr>
							</table>
						</div>
					</div>
					<hr>
				</div>
				{% endfor %}
				<div align="center">
					<span class="pgs">
						<a href="#">1</a>
						<a href="#">2</a>
						<a href="#">3</a>
						<a href="#">4</a>
						<a href="#">5</a>
						<a href="#">6</a>
						<a href="#">7</a>
						<a href="#">8</a>
						<a href="#">9</a>
						<a href="#">10</a>
						<a href="#">11</a>
					</span>
				</div>
				<div id="bttm">
					<h4>About us</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				</div>
			</div>
			<div class="col-sm-3">
				<h3 align="center">Popular</h3>
				<hr>
			</div>
		</div>
	</main>
{% endblock %}

vcinema/cinema/templates/cinema/login.html
{% extends 'cinema/base.html' %}
{% load static %}
{% block csslink %}
<link rel="stylesheet" type="text/css" href="{% static 'logreg.css' %}">
{% endblock %}
{% block maincontent %}
	<main class="container-fluid">
        <form method="POST">
			{% csrf_token %}
			<div align="center">
				<table>
					<tr>
						<td><label><b>Username</b></label></td>
						<td><input type="text" placeholder="Enter Username" name="username" required></td>
					</tr>
					<tr>
						<td><label><b>Password</b></label></td>
						<td><input type="password" placeholder="Enter Password" name="password" required></td>
					</tr>
				</table>
				<button type="submit">Login</button>
		    </div>
		</form>
	</main>
{% endblock %}

vcinema/cinema/templates/cinema/registration.html
{% extends 'cinema/base.html' %}
{% load static %}
{% block csslink %}
<link rel="stylesheet" type="text/css" href="{% static 'logreg.css' %}">
{% endblock %}
{% block maincontent %}
	<main class="container-fluid">
		<form method="post">
			{% csrf_token %}
			<div align="center">
				<table>
					<tr>
						<td><label><b>E-mail</b></label></td>
						<td><input type="email" placeholder="Enter E-mail" name="email" required></td>
					</tr>
					<tr>
						<td><label><b>Username</b></label></td>
						<td><input type="text" placeholder="Enter Username" name="username" required></td>
					</tr>
					<tr>
						<td><label><b>Password</b></label></td>
						<td><input type="password" placeholder="Enter Password" name="password" required></td>
					</tr>
					<tr>
						<td><label><b>Repeat Password</b></label></td>
						<td><input type="password" placeholder="Repeat Password" name="repass" required></td>
					</tr>
				</table>
				<button type="submit">Register</button>
		    </div>
		</form>
	</main>
{% endblock %}